name:                optimization
version:             1.0.0.0
github:              https://github.com/mbernat/optimization
license:             BSD3
author:              Marek Bernat
maintainer:          marek.bernat@gmail.com
copyright:           2017 Marek Bernat

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            This package provides a generic interface for stochastic optimization problems and strategies. A random search is included as a basic strategy. 
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/optimization#readme>

dependencies:
- base >= 4.7 && < 5
- random-fu == 0.2.7.0
- rvar == 0.2.0.3

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror

executables:
  optimization-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimization

tests:
  optimization-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimization
